In [3]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [8]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)